version: '3'

tasks:

  paralel_link_page:
    desc: Menjalankan script paralel_link_page.py
    cmds:
      - python paralel_link_page.py

  folder_paralel_link_web:
    desc: Menjalankan script folder_paralel_link_web.py
    cmds:
      - python folder_paralel_link_web.py

  paralel_elemen_html:
    desc: Menjalankan script paralel_elemen_html.py
    cmds:
      - python paralel_elemen_html.py

  run:
    desc: Menjalankan semua script secara beruntun (1 → 2 → 3)
    deps:
      - paralel_link_page
      - folder_paralel_link_web
      - paralel_elemen_html
